# After these number of moves, if nothing happens between the 3 idiots, then increment FAILURE_RATE_2
NO_OF_STEPS_1 = 200
NO_OF_STEPS_2 = 300
NO_OF_STEPS_3 = 500
NO_OF_STEPS_4 = 5000

NO_OF_GRAPHS = 100
NO_OF_RUNS = 30

NO_OF_NODES = 50

NO_OF_NEXT_STEP_PREDICTIONS_FOR_AGENT_2 = 1
PROB_OF_DISTRACTED_PREDATOR = 0.4

ENVIRONMENT_PATH = "Environment.json"
GRAPH_DIST_PATH = "Node Distances.json"
UTILITIES_PATH = "Utilities.npy"

BETA = 1
REWARD = 1

NO_OF_TIMES_I_WANT_UTILITIES_TO_BE_CONSISTENT = 2
